@GameStore.Api_HostAddress = http://localhost:5082

### Get all games list
GET {{['GameStore.Api_HostAddress']}}/games

### Get a single game by id
GET {{['GameStore.Api_HostAddress']}}/games/d9939446-3987-4c2e-9f34-e6995f05a456

### Create a new game
POST {{['GameStore.Api_HostAddress']}}/games
Content-Type: application/json

{
  "name": "Minecraft",
  "genre": "Kids and Family",
  "price": 19.99,
  "releaseDate": "2011-11-18"
}

### Update an existing game
PUT {{['GameStore.Api_HostAddress']}}/games/d9939446-3987-4c2e-9f34-e6995f05a456
Content-Type: application/json

{
  "name": "Street Fighter II Turbo",
  "genre": "Fighting",
  "price": 9.99,
  "releaseDate": "1992-07-15"
}